### ISSUE TITLE
其它问题 | 头像本地上传如何修改上传地址？文档案例中没有找到

### ISSUE THREAD

**Issue by ciuwa** [greper/d2-crud-plus#108]
![image](https://user-images.githubusercontent.com/69971005/101147765-c2038f80-3657-11eb-9313-a5bfe98ad45c.png)

**Comment by greper** [comment]
```
form: {
        component: {
            props:{
                uploader:{
                    type: 'form', //临时修改上传后端为form方式
                    action: 'xxx', // 临时修改form表单上传url
                }   
            }
        }   
      }   
```

**Comment by greper** [comment]
文档
http://greper.gitee.io/d2-crud-plus/guide/extends/file-uploader.html

http://greper.gitee.io/d2-crud-plus/guide/extends/uploader.html
