### ISSUE TITLE
BUG | D2CrudPlusExample 中开启了权限但点击菜单跳转到的页面没有导航，只有中间部分，看图

### ISSUE THREAD

**Issue by o624366705** [greper/d2-crud-plus#114]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
BUG | 你的标题
```

BUG | D2CrudPlusExample 中开启了权限但点击菜单跳转到的页面没有导航，只有中间部分，看图
![image](https://user-images.githubusercontent.com/7599032/101692817-b70f8b80-3aab-11eb-98b4-e128781db1e8.png)
图一

![image](https://user-images.githubusercontent.com/7599032/101692908-d60e1d80-3aab-11eb-9c08-4dd8747d16db.png)
图二、顶部导航和左侧导航，整个外围都没了

**Comment by greper** [comment]
根菜单要配置layoutAsideHeader，具体看菜单修改表单的前端组件字段的说明
