### ISSUE TITLE
建议把权限的部分放出来，前台和后台可以联动起来

### ISSUE THREAD

**Issue by o624366705** [greper/d2-crud-plus#12]
建议把前端权限的部分放出来，前台和后台可以联动起来

**Comment by greper** [comment]
后台也是开放的
具体请参考 http://greper.gitee.io/d2-crud-plus/guide/permission.html

**Comment by greper** [comment]
默认示例运行是没有开启权限管理的
运行 npm run dev:pm 就会开启
[权限管理示例运行](http://greper.gitee.io/d2-crud-plus/guide/quickstart.html#权限管理示例运行)

**Comment by arraycto** [comment]
已经可以运行的，需要启动后端的服务才能加载供参考
