### ISSUE TITLE
怎么使用 edit-quill 编辑器

### ISSUE THREAD

**Issue by crstudio** [greper/d2-crud-plus#126]
我是基于 `d2-admin-start-kit`  这个项目做的，`d2-crud-plus` 已经安装了，并且可以用，`quill`也装了，但是我按照示例配置的`column`，`form`里并没有渲染出`quill`编辑器，还是 `input`，请问我还需要在哪里`import`一下还是要怎么操作？
```javascript
{
  title: '内容',
  key: 'content',
  type: 'editor-quill',
  disabled: true
}
```

**Comment by greper** [comment]
是否有安装扩展插件 `D2pFullEditor`

http://greper.gitee.io/d2-crud-plus/guide/quickstart.html#_3-安装扩展插件

**Comment by crstudio** [comment]
原来是这样啊，不过大佬回复真及时，现在已经OK了，多谢多谢！！！！
