### ISSUE TITLE
功能升级 | 使用自定义模板打开弹窗的时候，希望可以增加一个给保存按钮自定义事件的选项

### ISSUE THREAD

**Issue by ib1ack** [greper/d2-crud-plus#127]
`customHandleBtnHandle({ index, row }) {
      this.getD2Crud().showDialog({
        mode: "edit", //当前打开模式,可选项[add,edit,view]
        rowIndex: index, //编辑或查看时，哪一行的数据
        template: {
          id: {
            value: row.id,
            component: {
              show: false
            }
          },
          manager_product: {
            title: "商品",
            slot: true
          }
        } //表单模版
      });
      this.mode = "related";
    }`
这边的需求是用自定义模板打开的弹窗，里面的逻辑并不涉及到主页面，但是现在按钮的逻辑是用的主页面的add,edit逻辑，所以就需要自定义mode，然后在对应的回调中判断，略显繁琐了。如果可以自定义事件，灵活性会比较高，逻辑也会更清楚

**Comment by greper** [comment]
已支持自定义mode
