### ISSUE TITLE
其它问题 | 我不会配置select的选项dict问题

### ISSUE THREAD

**Issue by ciuwa** [greper/d2-crud-plus#137]
![c96a814beaca7ed251f0018db2a1fa9](https://user-images.githubusercontent.com/69971005/105119191-ce11b680-5b0a-11eb-90e0-ac2361988f50.png)
![e1c75d2a87f69750384ed119bc52bd6](https://user-images.githubusercontent.com/69971005/105119199-d10ca700-5b0a-11eb-8387-d855d829051f.png)

看了文档不明白
我想配置select的option选项，但是是通过接口的某个字段获取的，不符合直接的返回的内容，需要对接口返回的格式化一下，我现在怎么写才能满足我的需求

**Comment by greper** [comment]
配置getData 里面去调用你的接口，返回dict 数组
然后配置 value 和label 分别为你的id字段名和name字段名
