### ISSUE TITLE
功能升级 | 希望avatar-cropper组件支持，文件还未上传完成时的检验

### ISSUE THREAD

**Issue by ib1ack** [greper/d2-crud-plus#141]
`rules: [
            {
              // 当有文件还未上传完成时，阻止表单提交，等待全部上传完成，才允许提交
              validator: D2pFileUploader.createAllUploadedValidator(
                vm.getFormComponentRef
              ),
              message: "还有文件正在上传，请等待上传完成，或删除它"
            }
          ]`
现在avatar-cropper组件配置这个rules会报错

**Comment by greper** [comment]
已支持
