### ISSUE TITLE
element tabel的双击事件是否能暴露出来

### ISSUE THREAD

**Issue by yaowenbin** [greper/d2-crud-plus#146]
功能开发 | 表格行双击事件支持

element table 中有 @row-dblclick 方法，是否能够暴露出来，业务中有双击行编辑、双击行跳转详情等常见需求

**Comment by greper** [comment]
手动在<d2-crud-x @cell-dblclick=xxx > 即可
https://greper.gitee.io/d2-crud-plus/d2-crud-x/events.html#cell-dblclick
