### ISSUE TITLE
文档相关 |  数据字典的类型说明不完整

### ISSUE THREAD

**Issue by John-Chan** [greper/d2-crud-plus#148]
原文档地址：http://d2-crud-plus.docmirror.cn/d2-crud-plus/guide/dict.html#%E6%95%B0%E6%8D%AE%E5%AD%97%E5%85%B8

我在看源代码时发现字典的UI渲染类型还可以支持`dict-switch`，`checkbox`，`radio`。我测试了一下发现确实有效过，它们的效果如下

### `dict-switch`
![dict-switch](https://user-images.githubusercontent.com/2360910/109842140-b9d1e500-7c84-11eb-9d1e-ed0a80b5b80a.png)

### `checkbox`
![checkbox](https://user-images.githubusercontent.com/2360910/109842131-b8082180-7c84-11eb-8714-8039257ac11c.png)

### `radio`
![radio](https://user-images.githubusercontent.com/2360910/109842146-ba6a7b80-7c84-11eb-9011-fa6560ec743d.png)

**Comment by greper** [comment]
我改一下
