### ISSUE TITLE
BUG|新增编辑时若前端未添加rule校验，导致后端报错返回的code不是0，这时候页面出现卡死现象

### ISSUE THREAD

**Issue by yaowenbin** [greper/d2-crud-plus#178]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
功能升级 | 你的标题
```

如果需要，在这里描述具体内容
![1622635935(1)](https://user-images.githubusercontent.com/20135897/120477919-e3fb8600-c3de-11eb-9941-82320e648a11.png)

按钮一直处于loading状态，导致页面也卡死了，所有地方都不能点击。。。控制台也没报错。。很神奇

**Comment by greper** [comment]
你做一个最小示例出来，我本地运行试试
