### ISSUE TITLE
BUG | editor类型不能同时出现多个

### ISSUE THREAD

**Issue by Septillions** [greper/d2-crud-plus#181]
![image](https://user-images.githubusercontent.com/29058283/121649934-9e6c4680-cacb-11eb-99da-44583b925758.png)
![image](https://user-images.githubusercontent.com/29058283/121649972-a7f5ae80-cacb-11eb-9bd4-171bb5c76829.png)
如图配置两个相同类型 editor 只会显示一个

**Comment by greper** [comment]
https://gitee.com/greper/d2-crud-plus/blob/master/packages/d2-crud-plus-example/src/business/modules/example/views/form/editor/crud.js
升级到最新版，配置不同的index即可
![image](https://user-images.githubusercontent.com/1687298/133378877-2eb08c3a-a6d2-4955-a9e6-2151d5efe747.png)
