### ISSUE TITLE
功能开发 | “编辑”时，可以 根据rowid 从后端重新拉取数据后再编辑吗？

### ISSUE THREAD

**Issue by DionSun** [greper/d2-crud-plus#212]
你好，在编辑对话框时，可以先重新从后端取数据后再编辑吗？
我想不到好的办法，只能自定义按钮，再调用showDialog来实现

**Comment by greper** [comment]
http://d2-crud-plus.docmirror.cn/d2-crud-plus/d2-crud-x/options.html#fetchdetail

**Comment by DionSun** [comment]
感谢大佬回复。
