### ISSUE TITLE
crud-search筛选后，通过crud-toolbar隐藏搜索区，再展示后，搜索条件重置按钮无法重置

### ISSUE THREAD

**Issue by YuuyaRin** [greper/d2-crud-plus#214]
http://preview.d2-crud-plus.docmirror.cn/D2CrudPlusExample/index.html#/demo/form/text
以这个示例为例：
输入筛选条件--》点击查询--》点击右侧toolbar隐藏筛选组件--》再点击展示筛选组件--》点击查询旁的重置button--》筛选条件并未重置为空，而是重置为筛选区域被隐藏前的状态
请问这个情况有没有办法解决，这么重置回crud-search最初的状态

**Comment by greper** [comment]
这是因为筛选框是被v-if控制显示和隐藏，实际上是重新被创建，当重新被创建时，它使用了当前的查询条件作为默认值。所以出现了这个问题。
你可以将`:search.sync="crud.searchOptions.show"`修改为`:search.sync="crud.searchOptions.show2`
然后给crud-search配置 `v-show = crud.searchOptions.show2`来控制搜索框的显隐
