### ISSUE TITLE
其它问题 | showOverflowTooltip功能无效？

### ISSUE THREAD

**Issue by projectnikke** [greper/d2-crud-plus#236]
按照文档说明配置: columns下的showOverflowTooltip为TRUE时并没有当内容过长被隐藏时显示 tooltip，无论如何都不能生效

**Comment by greper** [comment]
http://preview.d2-crud-plus.docmirror.cn/D2CrudPlusExample/index.html#/demo/form/group
看这个示例

**Comment by projectnikke** [comment]
> http://preview.d2-crud-plus.docmirror.cn/D2CrudPlusExample/index.html#/demo/form/group 看这个示例

![image](https://user-images.githubusercontent.com/105738098/196960119-f565a679-f25b-40eb-92b0-d93b6312425c.png)
参照了示例，我type默认是input，表格内容依然会分行，不知道是哪里的问题。
![image](https://user-images.githubusercontent.com/105738098/196960712-47cb22bb-5888-417b-989a-569582fafdc9.png)

**Comment by Krypln** [comment]
我也遇到了类似的情况，查看
![image](https://github.com/greper/d2-crud-plus/assets/34902159/2163bf85-72be-442b-908a-090d24ea6554) 中的元素发现，使用的是el-table .
而我使用的是vxe-table 
![image](https://github.com/greper/d2-crud-plus/assets/34902159/e1de25d7-2fb9-43fb-8b87-561d3024a54b)

本地
![image](https://github.com/greper/d2-crud-plus/assets/34902159/d3a54862-312e-40da-9df1-4e5db3364490)


所以  删除了 tableType
![image](https://github.com/greper/d2-crud-plus/assets/34902159/f995cb50-c80b-4601-90ad-3cba7ca86ab1)
就可以了。
![image](https://github.com/greper/d2-crud-plus/assets/34902159/0a56842a-0eca-4103-a72f-888d6de93eb7)

**Comment by Krypln** [comment]
或者修改showOverflowTooltip 为  showOverflow
![image](https://github.com/greper/d2-crud-plus/assets/34902159/bb3b9ffe-e654-4d37-b28b-91d73681ad76)
