### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#29]
1个月之前用了大佬的框架，随着大佬的功能越发的强大。
请问，现在要用新功能的话，是不是得重新来一遍，还是说重新npm即可，能兼容升级
感谢大佬

**Comment by greper** [comment]
如果你用d2-crud-plus-example做为你的启动项目，升级就比较麻烦一点（可以参考文档 
 http://greper.gitee.io/d2-crud-plus/guide/upgrade.html）
如果是用的原版d2-admin，根据快速开始集成进来的，直接更新依赖的版本即可，基本上兼容的（可能某些破坏性变更需要稍作修改）

**Comment by arraycto** [comment]
明白。尝试中
