### ISSUE TITLE
bug，重复请求bug

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#33]
项目查询时候，发现了重复请求

复现地址：http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/permission/platform

复现步骤： 搜索框输入 admin，迅速的按下查询按钮

看谷歌浏览器的控制台

两条请求记录

**Comment by greper** [comment]
搜索做了延迟自动查询功能，搜索框中的value值变化500ms之后自动发起查询
```
searchOptions: { //查询配置参数
    debounce:{ //自动查询防抖,debounce:false关闭自动查询
      wait: 500, //延迟500毫秒
      ... //options : https://www.lodashjs.com/docs/lodash.debounce
    }   
  }
```

**Comment by arraycto** [comment]
明白，需要可以配置
