### ISSUE TITLE
颜色设定或者标签的类型设置

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#36]
设置样式：http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/demo/form/toolbar
如图的怎么设置tag的类型，目前都是蓝色的，默认的，例如有的判断如果name=admin红色，其他的蓝色

![QQ截图20200808200750](https://user-images.githubusercontent.com/37463247/89710120-eb1a5900-d9b2-11ea-8513-c05a759f0a85.png)

请问大佬如何设置，没找到api，抱歉再次打扰您。

**Comment by greper** [comment]
方法1
获取的字典数据中，带上color即可，可选值【primary,success,danger,warning,info】
`data:[{value:xx,label:xx,color:'success'}]`

方法2
如果后台不方便返回color，可以给字段配置自动染色
` columns:[{component:{props:{color:'auto'}}}]`

方法3
或者手动设置
```
columns:[
{
 component:{
  props:{
    onReady(context){   //{component, data, setDictData, form}
     context. data[0].color='success'
     context.setDictData(data)
    }
  }}}
]
```
