### ISSUE TITLE
组件bug：列表字典生效，但是新增和更新的时候失效

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#37]
如题：
![QQ截图20200808222737](https://user-images.githubusercontent.com/37463247/89712903-73eec000-d9c6-11ea-847d-e07fb7161c98.png)
![QQ截图20200808222806](https://user-images.githubusercontent.com/37463247/89712904-75b88380-d9c6-11ea-8aba-82828b1bc036.png)

配置如下：
crud.js

```
   {
      title: '角色',
      key: 'roleId',
      search: {
        disabled: true //【可选】true禁止查询,默认为false
      }, 
      type: 'select', //字段类型为选择框
      form: { //配置添加和编辑，根据form的配置自动生成addTemplate和editTemplate
        rules: [ //【可选】添加和修改时的校验规则，不配置则不校验
          {
            required: true,
            message: '请选择角色'
          }
        ]
      },
      dict: {
        // 这里配置远程获取字典数据的请求地址
        url: 'rest/role/commonList',
        value: 'id', // 数据字典中value字段的属性名
        label: 'roleLabel' // 数据字典中label字段的属性名
      }

    }
```

**Comment by greper** [comment]
请确认value的数据类型，int和string是不相等的

**Comment by arraycto** [comment]
已确认，value为“1”，是属于两个数值均为string， 本身数据id为string，对比的字典也为string，仍旧出现上述bug，必须都为int？

**Comment by arraycto** [comment]
下来正常，下拉的回显不对哈

**Comment by arraycto** [comment]
![list](https://user-images.githubusercontent.com/37463247/89733689-e1175980-da89-11ea-9301-fbb7b77fcd6e.png)
![dict](https://user-images.githubusercontent.com/37463247/89733694-e5437700-da89-11ea-96c7-fb3b6f188bba.png)
