### ISSUE TITLE
🤔 提问 | 引用页面问题，存在使用困惑

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#43]
情况是这样的。不同的tab，切换不同的表格（表格的头和内容均不同），没有做成统一的compents，请问在tab切换的时候如何引用，从而达到，不同的tab切换不同的表格的效果。

例如：https://element.eleme.cn/#/zh-CN/component/tabs

其中上面例子中【配置管理】的表格和【配置管理】的表格字段，内容完全不同

**Comment by arraycto** [comment]
按照传统的引入方式无效：如下无效


```
我需要在App.vue中引入HelloWorld.vue
//引入导航栏组件 Nav 相当于一个变量，名字可以随意 后面路径一定要对

import Nav from '@/components/HelloWorld.vue'
1
//注册组件 放在default{}里 组件名称要与引入的变量 Nav_Bar相同

components: {
      Nav_Bar
  },
1
2
3
//使用组件

<Nav_Bar></Nav_Bar/>
```

**Comment by greper** [comment]
这跟d2-crud无关吧？
你是想要在tab页切换两个d2-crud？
你得把两个d2-crud做成组件，然后在这个tab页面引入它们

**Comment by arraycto** [comment]
已经做成了组件，存在原生和d2-crud冲突问题
![搜狗截图20年08月20日1130_2](https://user-images.githubusercontent.com/37463247/90713779-a9ee4700-e2d8-11ea-8667-ad1983635058.png)

**Comment by arraycto** [comment]
同时一个页面同时使用两个curd组件时候，出现错乱且不能翻入el-tabs中，el-tabs中根本不显示额，请问大佬这种该怎么搞
```
 <div>
       <tients></tients>
    </div>
    <div>
        <history></history>
    </div>
```
![搜狗截图20年08月20日1134_3](https://user-images.githubusercontent.com/37463247/90713945-18cba000-e2d9-11ea-9c05-ea5c2b4100fc.png)

**Comment by arraycto** [comment]
![搜狗截图20年08月20日1138_4](https://user-images.githubusercontent.com/37463247/90714180-aad3a880-e2d9-11ea-926a-bcc2fd5db298.png)

**Comment by greper** [comment]
http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/demo/form/nestTable
已增加示例
