### ISSUE TITLE
 提问 | 文件上传返回500报错Uncaught TypeError: option.onError is not a function

### ISSUE THREAD

**Issue by sunxingsong** [greper/d2-crud-plus#44]
![image](https://user-images.githubusercontent.com/6611189/90339479-92d2ff00-e023-11ea-82a4-ed45329ef3f5.png)
![image](https://user-images.githubusercontent.com/6611189/90339536-e9d8d400-e023-11ea-9edd-646065d5082a.png)

上传返回500报错Uncaught TypeError: option.onError is not a function，但是页面文件显示100%

**Comment by greper** [comment]
已修复
