### ISSUE TITLE
👾 BUG | 懒加载展开行在展开后就不会重置状态了，无论点搜索还是分页

### ISSUE THREAD

**Issue by wuhao-max** [greper/d2-crud-plus#45]
![image](https://user-images.githubusercontent.com/39900695/90583381-9375bc00-e202-11ea-8878-a85de306fb91.png)
这个懒加载在展开后，切换分页后或者重新搜索后懒加载展开行状态还是展开的，而element-ui的会重置懒加载状态。
重新点击搜索后懒加载的那一行还是展开状态，必须重新刷新页面。

**Comment by greper** [comment]
在第二页仍然有hasChildren的数据下，el-table是不会清除掉懒加载状态的。
需要手动清理
```
// 手动更新加载项
        const data = this.getD2Crud().$refs.elTable.store.states.treeData
        if (data != null) {
          const item = data[row.parentId]
          if (item != null) {
            item.loaded = false
            item.expanded = false
          }
        }
```
