### ISSUE TITLE
🤔 提问 | 每次请求之后，可以不可不更新pageSize

### ISSUE THREAD

**Issue by qq1037305420** [greper/d2-crud-plus#49]
后端不返回每页个数
如果用返回数量（records.length）作为pageSize，加了查询条件之后 重置 pageSize不重制。

**Comment by greper** [comment]
[参考文档](http://greper.gitee.io/d2-crud-plus/guide/structure.html#%E5%A6%82%E6%9E%9C%E4%BD%A0%E5%90%8E%E7%AB%AF%E8%BF%94%E5%9B%9E%E6%AF%94%E8%BE%83%E5%A5%87%E8%91%A9)
可以在pageRequest里面修改返回结果

**Comment by qq1037305420** [comment]
但是这样有点麻烦了 每个请求都要写
