### ISSUE TITLE
显示优化 | 字典容易泄露ID或者用户体验二次加载感觉问题，供参考

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#52]
复现地址：
http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/usersphere/user

问题描述：
由于网络的波动，刷新带有select的字典页面，容易先看到ID，稍后看到ID对应的汉字。
如果网络刚好卡住，ID容易泄露或者不美观，用户有一种二次加载的感觉，不知道能否修复。供参考。

**Comment by greper** [comment]
已修复，在没有加载完成之前，将不显示任何东西

**Comment by arraycto** [comment]
赞赞。我更新尝试一下。感谢

**Comment by arraycto** [comment]
请问一下这个是什么原理修复的？大佬能否请教一下思路。

**Comment by greper** [comment]
加了loading状态，组件创建就loading=true，加载完改成loading=false，根据loading状态不展示任何数据即可

**Comment by arraycto** [comment]
赞赞，教师节快乐！
