### ISSUE TITLE
示例相关 | 兼容性问题，多框架兼容

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#58]
1、d2-crud-plus在d2-admin中运行无问题，请问目前d2-crud-plus是否可以单独使用？
2、例如配合：https://github.com/PanJiaChen/vue-element-admin进行插件融合使用。

**Comment by greper** [comment]
理论上d2-crud-plus不依赖d2-admin，在以element-ui为基础的框架中都能运行。

**Comment by arraycto** [comment]
可以单独独立出来，以插件的形式进行，热插拔，供参考
