### ISSUE TITLE
其它问题 | 动态修改字典数据

### ISSUE THREAD

**Issue by SLin0218** [greper/d2-crud-plus#59]
你好，我需要动态修改表单中 `select` 组件的数据，
字典配置 `data` 属性一些默认数据，然后根据点击列表来修改字典，
添加一些内容，发现没法重新加载配置。

**Comment by greper** [comment]
直接修改dict.data无法动态修改select的选项数据

方式1： 配置DictSelect组件的options(数据结构与dict.data一致)，options参数比dict.data具有更高优先级，并且可以动态修改
```
valueChange (key, value, form, { getColumn, mode, component, immediate, getComponent }) {
       getColumn.component.props.options=[{字典数据}]
 },
```
方式2： 参考选择联动http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/demo/form/linkage
```
valueChange (key, value, form, { getColumn, mode, component, immediate, getComponent }) {
            form.city = undefined // 将“city”的值置空
            form.county = undefined// 将“county”的值置空
            if (value) {
              getComponent('city').reloadDict() // 执行city的select组件的reloadDict()方法，触发“city”重新加载字典
            }
          },
```
DictSelect组件ref暴露如下一些方法可以操作字典：
```
component.clearDict()  //清除字典
component.loadDict() //加载字典
component.setDictData(data) //修改字典数据
```

方式3：动态修改dict.url 也会触发字典重载
```
valueChange (key, value, form, { getColumn, mode, component, immediate, getComponent }) {
       getColumn.component.props.dict.url=dict.url?params=xxx //不同的参数获取不同的字典列表
 },

```

**Comment by SLin0218** [comment]
@greper 谢谢，在触发 `addRow` 后，需要给树结构添加一个父菜单 `id`。
翻了下文档，没找到方法。`dialog-open` 修改数据没有效果。

**Comment by greper** [comment]
`dialog-open` 是在对话框打开之前执行的
`dialog-opened` 是在对话框打开之后执行的
你应该在`dialog-opened` 里面做修改（不过dict的加载是异步的，可能你在这里也无法成功修改到）

**Comment by greper** [comment]
如果是仅仅只是要修改后台返回的字典数据结构，你可以写在 
```
props:{
  onReady(context){
     context.data // 修改它
  }
} 
```

**Comment by SLin0218** [comment]
1. 已经无法正常打开，我尝试用手机网络，和 `wifi vpn`，都不行。
`http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/demo/form/linkage`
`IP：117.21.225.226`

2. `getComponent` 可以直接使用吗，我想在选择 `row` 的时候，修改 `dict` 数据。
```
     {
        disabled: true,
        title: vm.$t('domain.sParentName.label'),
        key: 'iParentId',
        type: 'select',
        form: {
          editDisabled: true,
          component: {
            name: 'dict-select'
          }
        },
        dict: {
          data: [{ value: 0, label: vm.$t('domain.sDomainName.root') }],
          cache: false
        }
      }
```

3. 我没有使用`d2-admin`，其中一些图标不存在，是否存在配置可以替换或禁用，`search` 中的图标。
4. 树表格中，添加数据的时候需要给数据加上父节点 `id`，怎样才能在对话框打开之前添加 `id` 数据，
还是添加数据这个处理方法需要自己实现。

**Comment by greper** [comment]
你加我微信吧
http://greper.gitee.io/d2-crud-plus/guide/contact.html

**Comment by SLin0218** [comment]
十分感谢
通过微信沟通问题已经解决。
重写 `dialog-opened`， 通过 暴露方法 `getEditFormTemplate` 直接修改 `component.props.dict' 数据
![image](https://user-images.githubusercontent.com/23139501/93869556-8581f200-fcfe-11ea-948f-763052a7a0b6.png)

![image](https://user-images.githubusercontent.com/23139501/93869506-7438e580-fcfe-11ea-8538-1629bc455aa3.png)
