### ISSUE TITLE
使用官方示例请求后台接口报错

### ISSUE THREAD

**Issue by githinkcn** [greper/d2-crud-plus#6]
数据:{
  "code": 0,
  "msg": null,
  "data": {
    "records": [
      {
        "id": "fd6138ed867b9fd38faa891725754e27",
        "createBy": "string",
        "createTime": "2020-04-28 09:16:26",
        "updateBy": "string",
        "updateTime": null,
        "delFlag": 0,
        "username": "22222222222222",
        "password": "string",
        "nickName": "string",
        "phone": "string",
        "email": "string",
        "address": "string",
        "sex": "1",
        "passStrength": "1",
        "avatar": "string",
        "type": 0,
        "status": 0,
        "description": "string",
        "deptId": "string",
        "deptName": null,
        "roles": null,
        "roleKeys": null
      }
    ],
    "total": 1,
    "size": 10,
    "current": 1,
    "orders": [],
    "hitCount": false,
    "searchCount": true,
    "pages": 1
  }
}

错误：
![image](https://user-images.githubusercontent.com/13462780/81577594-30db7b80-93dc-11ea-987b-fad4a34fd229.png)

**Comment by githinkcn** [comment]
比对了一下返回的数据格式，自己有封装了一些

**Comment by CrassusX** [comment]
请求数据方式能否放开呢，因为返回数据样式有不同方式，按照你的设计，后台不按照这种方式返回呢

**Comment by greper** [comment]
你可以在api里修改返回结果，来适应框架所需
```
export function GetList (query) {
  return request({
    url: '/date/page',
    method: 'get',
    data: query
  }).then(ret=>{
//在这里修改成框架所需要的结构
//你可以抽象出一个util方法，避免重复写这部分代码
return ret
})
}
```
