### ISSUE TITLE
BUG | IE兼容

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#60]
现在一些企业，还是存在，尤其领导的电脑使用IE的情况，使用过程中发现如下问题：

兼容问题：不能兼容IE类浏览器，目前测试的IE11  ，win10
复现地址：http://qiniu.veryreader.com/D2CrudPlusExample/index.html

**Comment by greper** [comment]
具体问题是什么，我这边测试是正常的

**Comment by arraycto** [comment]
![猎豹截图20201009215827](https://user-images.githubusercontent.com/37463247/95592071-b8581400-0a7a-11eb-9f83-7351b5795be6.png)

**Comment by arraycto** [comment]
大佬，如上所示

**Comment by greper** [comment]
给你项目的vue.config.js配置如下代码试试
```
module.exports = {
// 解决ie打不开的问题
  transpileDependencies: ['d2p-extends']
}
```
