### ISSUE TITLE
其它问题 | 如何固定表格的操作列？

### ISSUE THREAD

**Issue by puppyhang** [greper/d2-crud-plus#61]
看了example里面的用法没找到我要的效果，假如我的表中最后一列用showRemoveButton等参数显示了操作列，当列太多的时候怎么固定呀？
麻烦作者回复一下

**Comment by greper** [comment]
配置 rowHandle:{ fixed:'right'} 即可
参考文档： http://greper.gitee.io/d2-crud-plus/d2-crud-x/row-handle.html#fixed
