### ISSUE TITLE
显示优化 | crud-toolbar 的文字显示

### ISSUE THREAD

**Issue by vampcheah** [greper/d2-crud-plus#63]
crud-toolbar 里面的列设置做得很棒，可是不支持多语言。
建议多使用 prop 传入 text 方便控制标题及按钮的文字显示。

**Comment by greper** [comment]
d2-crud-plus@1.16.6 已支持
http://greper.gitee.io/d2-crud-plus/guide/components/crud-toolbar.html#crud-toolbar

**Comment by vampcheah** [comment]
> d2-crud-plus@1.16.6 已支持
> http://greper.gitee.io/d2-crud-plus/guide/components/crud-toolbar.html#crud-toolbar

太好了，感谢
