### ISSUE TITLE
BUG | 有关初始化（或加载数据）从created推迟到mounted

### ISSUE THREAD

**Issue by vampcheah** [greper/d2-crud-plus#64]
- 文档似乎有错误，应该是 _OnCreated() 和 _doStart()。已经测试了，是运行次序可行的。
- 但是使用 vex-table的话，会出现 [vxe-table] 参数 "column.label" 已废弃，请使用 "column.title"。
- 如果切换 el-table，依然会出现错误。查询的区域无法显示。

**Comment by greper** [comment]
* 确实有错误，感谢指出
* vxe-table的问题，你需要升级crud-plus 和crud-x的版本
* 查询的区域无法显示应该是另外一个问题
