### ISSUE TITLE
显示优化 | 嵌套表格首次加载刷新页面

### ISSUE THREAD

**Issue by TanyLiver** [greper/d2-crud-plus#65]
示例中嵌套表格首次打开，点击嵌套表格删除按钮后页面会刷新，后续操作才可以正常，当新开窗口 首次又会刷新页面。

**Comment by greper** [comment]
好像部署d2-crud-plus 1.16.7之后，已经好了。
http://qiniu.veryreader.com/D2CrudPlusExample/index.html?#/demo/form/nestTable
我没有特意去修复它，你升级以后再测试一下试试

**Comment by TanyLiver** [comment]
先访问首页
http://qiniu.veryreader.com/D2CrudPlusExample/index.html
然后通过菜单点击进去 还是会有首次刷新问题

**Comment by greper** [comment]
2.12.0 已修复
