### ISSUE TITLE
功能升级 | initColumns 初始化数据

### ISSUE THREAD

**Issue by vampcheah** [greper/d2-crud-plus#66]
在多次call _doStart() 的情况下，table 和 crudOptions.columns 的数据都是完好的，但是 Search / addTemplate / editTemplate / viewTemplate 都出现了重复key+item的现象。

建议在 initColumns 里面进行更全面的初始化，例如 crud.viewTemplate = []

**Comment by greper** [comment]
d2-crud-plus@1.16.7 已支持
