### ISSUE TITLE
其他问题|d2-crud-plus-example下的路由modules怎么使用

### ISSUE THREAD

**Issue by justpic** [greper/d2-crud-plus#67]
```
其它问题 | d2-crud-plus-example下的路由modules怎么使用
```
https://github.com/greper/d2-crud-plus/tree/master/packages/d2-crud-plus-example/src/router/modules下对应的view在哪儿？

**Comment by greper** [comment]
那个modules没有用的，从d2-admin复制过来，忘记删掉了。
对应的view请看这个项目：https://github.com/d2-projects/d2-admin
