### ISSUE TITLE
能不能实现表格的折叠功能expand，在普通版本没发现列的扩展组件的点击事件，这个看到了不错

### ISSUE THREAD

**Issue by CrassusX** [greper/d2-crud-plus#7]

**Comment by greper** [comment]
https://element.eleme.cn/#/zh-CN/component/table#zhan-kai-xing
你是指的这个功能吗？

**Comment by greper** [comment]
你好，行展开功能目前已实现，请升级d2-crud-x,d2-crud-plus体验
示例地址
http://qiniu.veryreader.com/D2CrudPlusExample/index.html#/form/column
