### ISSUE TITLE
示例相关 | 新增按钮和查询按钮相关

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#71]
请问：新增按钮和查询按钮相关，非每一行后面的新增
如何把每个页面的新增的颜色或者内容，如“”新增“”变成“”添加“”两个字 ，同时变成thin
请问在哪里配置，配置如下无效：
```
 add: {
        thin: true,
        text: null,
          type: 'info'
          },

```

**Comment by greper** [comment]
新增按钮是写在index.vue里面的 ，你自己直接改就好，不需要修改配置

**Comment by arraycto** [comment]
惯性思维搞得，的确的确。请问，查询按钮呢，是不是需要配置
