### ISSUE TITLE
显示优化 | 查询界面优化和主题问题

### ISSUE THREAD

**Issue by arraycto** [greper/d2-crud-plus#73]
您好：是这样的，由于历史系统主题统一问题，需要将所有的按钮默认颜色变为plain的效果，请问：
1）查询按钮如何更改颜色和添加plain，这个和新增不同，属于已经封装了的，没找到更改入口，参考plian样式：https://element.eleme.cn/#/zh-CN/component/button

```
<el-row>
  <el-button plain>朴素按钮</el-button>
  <el-button type="primary" plain>主要按钮</el-button>
  <el-button type="success" plain>成功按钮</el-button>
  <el-button type="info" plain>信息按钮</el-button>
  <el-button type="warning" plain>警告按钮</el-button>
  <el-button type="danger" plain>危险按钮</el-button>
</el-row>
```

2）查询状态栏，默认是展开的，点击toolbar可以隐藏，问题是：如何默认隐藏，点击toolbar可以展开？
再次感谢您的耐心指导，大佬辛苦。

**Comment by greper** [comment]
1. 2.12.0已支持
2. 默认隐藏配置search.show=false
