### ISSUE TITLE
功能开发 |  希望能开发一个 table 点击整列进行编辑功能

### ISSUE THREAD

**Issue by lijiliang** [greper/d2-crud-plus#78]
希望能开发一个可以点击整列进行编辑的功能

效果如图：

<img src="https://upload-images.jianshu.io/upload_images/2675631-8ca9fdb20e872175.gif?imageMogr2/auto-orient/strip|imageView2/2/w/864/format/webp">

**Comment by greper** [comment]
2.13.2 已支持行编辑功能
http://preview.d2-crud-plus.docmirror.cn/D2CrudPlusExample/index.html#/demo/form/lineEdit
