### ISSUE TITLE
功能升级 | 图片上传 buildUrl 支持返回 Promise 类型

### ISSUE THREAD

**Issue by Septillions** [greper/d2-crud-plus#86]
Alioss 文件地址需要 STS 签名，由于首先需要请求服务器拿临时 STS 相关信息再 signatureUrl ，返回的是 Promise 类型，需要buildUrl 支持 return Promise

**Comment by greper** [comment]
太多地方用到buildUrl，其中很多是computed里面调用的，不太好支持promise。
建议事先获取到sts，保存在data里面，然后再在buildUrl里面同步签名url

**Comment by Septillions** [comment]
可以换一种思路，目前 uploader 组件是上传完成后直接给 column 赋新值，有没有地方可以在上传完成后处理新值，比如 el-upload 有 on-success，我直接配置在 elProps 下并不能生效。不知道是不是我用的不对。

**Comment by greper** [comment]
2.13.4支持配置successHandle,在上传完成后处理新值
