### ISSUE TITLE
其它问题 | 我想实现"删除"操作按钮根据状态不用而作用不同. 请问如何实现

### ISSUE THREAD

**Issue by kys1230** [greper/d2-crud-plus#92]
我的数据是逻辑删除, 因此我希望根据删除状态判断, 已删除的数据, 删除按钮变为"恢复"按钮, 并发送单独的请求用于告知后端服务修改状态. 请问应该如何实现?

**Comment by kys1230** [comment]
如果是自定义按钮来实现, 那有什么办法来根据每行数据的状态来控制按钮的隐藏与展示.

**Comment by greper** [comment]
show 可以配置为一个方法，具体请看文档
http://greper.gitee.io/d2-crud-plus/guide/options.html#crudoptions

**Comment by kys1230** [comment]
实在抱歉. 没有注意到 show 的相关介绍. 我去尝试. 感谢你的及时回复.
