### ISSUE TITLE
BUG | index.js?ac5b:25 TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by ciuwa** [greper/d2-crud-plus#95]
![image](https://user-images.githubusercontent.com/69971005/99960333-8949f780-2dc7-11eb-9187-746a464631fc.png)
当为抽屉模式的时候 会报错

**Comment by ciuwa** [comment]
type: "drawer",

**Comment by greper** [comment]
错误日志截图发上来

**Comment by ciuwa** [comment]
> 错误日志截图发上来

![image](https://user-images.githubusercontent.com/69971005/100031389-7ddee680-2e30-11eb-932c-051ee158a249.png)

![image](https://user-images.githubusercontent.com/69971005/100031410-8df6c600-2e30-11eb-992a-dea0b895a52f.png)

**Comment by greper** [comment]
照着示例，把全屏和拖拽关了

**Comment by ciuwa** [comment]
> 照着示例,把全屏和拖拽关了

解决
