### ISSUE TITLE
其它问题 | 能不能做如图需求

### ISSUE THREAD

**Issue by ciuwa** [greper/d2-crud-plus#98]
就是没有表格的这种
![image](https://user-images.githubusercontent.com/69971005/100067674-87d50980-2e71-11eb-861c-2961734e3e10.png)

**Comment by ciuwa** [comment]
![image](https://user-images.githubusercontent.com/69971005/100067978-e26e6580-2e71-11eb-95bf-2d558e5ee020.png)

**Comment by greper** [comment]
这种自己用element-ui写更快

**Comment by ciuwa** [comment]
ok
